IMAGE_INSTALL += " network-conf"
IMAGE_INSTALL += " ssh-conf"
IMAGE_INSTALL += " hello-world"
IMAGE_INSTALL += " python3-flask"
IMAGE_INSTALL += " python3-unittest"
IMAGE_INSTALL += " python3-dev"
IMAGE_INSTALL += " cunit"
IMAGE_INSTALL += " lsm9ds1"
