/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "example_constants.h"

namespace Test {

const exampleConstants g_example_constants;

exampleConstants::exampleConstants() {
}

} // namespace

